"""Configuration loading and defaults for originweave.

The default configuration lives in the project-local ``originweave.toml`` and is
generated by ``originweave init``. Reads use the standard-library ``tomllib``;
writes use ``tomli-w``.

CLI flags take precedence over config values; missing keys fall back to the
defaults defined here.
"""

from __future__ import annotations

import os
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any

import tomli_w

CONFIG_FILENAME = "originweave.toml"
LIVE_ENV_VAR = "ORIGINWEAVE_LIVE"

ALLOWED_SEARCH_PROVIDERS: frozenset[str] = frozenset({"exa", "parallel"})
ALLOWED_PROMPT_PROVIDERS: frozenset[str] = frozenset({"local", "langfuse"})

_TRUE_VALUES: frozenset[str] = frozenset({"1", "true", "yes", "on"})
_FALSE_VALUES: frozenset[str] = frozenset({"0", "false", "no", "off"})

_TOP_LEVEL_KEYS: frozenset[str] = frozenset({"live", "hitl", "capability", "budget", "run"})
_TABLE_KEYS: dict[str, frozenset[str]] = {
    "live": frozenset({"enabled"}),
    "hitl": frozenset({"auto"}),
    "capability": frozenset({"search", "prompt"}),
    "capability.search": frozenset({"provider"}),
    "capability.prompt": frozenset({"provider", "directory"}),
    "budget": frozenset({"max_steps", "max_wall", "max_cost"}),
    "run": frozenset({"dir"}),
}


class ConfigError(ValueError):
    """Raised when a configuration value is missing or invalid."""


@dataclass(frozen=True)
class LiveConfig:
    enabled: bool = False


@dataclass(frozen=True)
class HitlConfig:
    auto: bool = False


@dataclass(frozen=True)
class SearchConfig:
    provider: str = "exa"


@dataclass(frozen=True)
class PromptConfig:
    provider: str = "local"
    directory: str = "prompts"


@dataclass(frozen=True)
class CapabilityConfig:
    search: SearchConfig = field(default_factory=SearchConfig)
    prompt: PromptConfig = field(default_factory=PromptConfig)


@dataclass(frozen=True)
class BudgetConfig:
    max_steps: int = 60
    max_wall: str = "10m"
    max_cost: float = 2.0


@dataclass(frozen=True)
class RunConfig:
    dir: str = "runs"


@dataclass(frozen=True)
class Config:
    live: LiveConfig = field(default_factory=LiveConfig)
    hitl: HitlConfig = field(default_factory=HitlConfig)
    capability: CapabilityConfig = field(default_factory=CapabilityConfig)
    budget: BudgetConfig = field(default_factory=BudgetConfig)
    run: RunConfig = field(default_factory=RunConfig)

    def to_dict(self) -> dict[str, Any]:
        """Render the config as a plain dict suitable for TOML serialisation."""
        return {
            "live": {"enabled": self.live.enabled},
            "hitl": {"auto": self.hitl.auto},
            "capability": {
                "search": {"provider": self.capability.search.provider},
                "prompt": {
                    "provider": self.capability.prompt.provider,
                    "directory": self.capability.prompt.directory,
                },
            },
            "budget": {
                "max_steps": self.budget.max_steps,
                "max_wall": self.budget.max_wall,
                "max_cost": self.budget.max_cost,
            },
            "run": {"dir": self.run.dir},
        }

    def validate(self) -> None:
        """Validate cross-field invariants; raise :class:`ConfigError` on failure."""
        search = self.capability.search.provider
        if search not in ALLOWED_SEARCH_PROVIDERS:
            raise ConfigError(
                f"unknown search provider {search!r}; "
                f"expected one of {sorted(ALLOWED_SEARCH_PROVIDERS)}"
            )
        prompt = self.capability.prompt.provider
        if prompt not in ALLOWED_PROMPT_PROVIDERS:
            raise ConfigError(
                f"unknown prompt provider {prompt!r}; "
                f"expected one of {sorted(ALLOWED_PROMPT_PROVIDERS)}"
            )
        if self.budget.max_steps <= 0:
            raise ConfigError(f"budget.max_steps must be > 0, got {self.budget.max_steps}")
        if self.budget.max_cost < 0:
            raise ConfigError(f"budget.max_cost must be >= 0, got {self.budget.max_cost}")


def _as_mapping(value: Any, where: str) -> Mapping[str, Any]:
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ConfigError(f"{where} must be a TOML table")
    return value


def _as_str(value: Any, where: str, default: str) -> str:
    if value is None:
        return default
    if not isinstance(value, str):
        raise ConfigError(f"{where} must be a string")
    return value


def _as_bool(value: Any, where: str, default: bool) -> bool:
    if value is None:
        return default
    if not isinstance(value, bool):
        raise ConfigError(f"{where} must be a boolean")
    return value


def _as_int(value: Any, where: str, default: int) -> int:
    if value is None:
        return default
    if not isinstance(value, int) or isinstance(value, bool):
        raise ConfigError(f"{where} must be an integer")
    return value


def _as_float(value: Any, where: str, default: float) -> float:
    if value is None:
        return default
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ConfigError(f"{where} must be a number")
    return float(value)


def _check_keys(table: Mapping[str, Any], where: str, allowed: frozenset[str]) -> None:
    unknown = sorted(set(table) - allowed)
    if unknown:
        label = where or "config"
        raise ConfigError(f"{label}: unknown key(s) {unknown}; allowed: {sorted(allowed)}")


def from_dict(data: Mapping[str, Any]) -> Config:
    """Build a :class:`Config` from a parsed TOML mapping, filling in defaults."""
    defaults = Config()
    _check_keys(data, "", _TOP_LEVEL_KEYS)
    live = _as_mapping(data.get("live"), "live")
    hitl = _as_mapping(data.get("hitl"), "hitl")
    capability = _as_mapping(data.get("capability"), "capability")
    search = _as_mapping(capability.get("search"), "capability.search")
    prompt = _as_mapping(capability.get("prompt"), "capability.prompt")
    budget = _as_mapping(data.get("budget"), "budget")
    run = _as_mapping(data.get("run"), "run")

    _check_keys(live, "live", _TABLE_KEYS["live"])
    _check_keys(hitl, "hitl", _TABLE_KEYS["hitl"])
    _check_keys(capability, "capability", _TABLE_KEYS["capability"])
    _check_keys(search, "capability.search", _TABLE_KEYS["capability.search"])
    _check_keys(prompt, "capability.prompt", _TABLE_KEYS["capability.prompt"])
    _check_keys(budget, "budget", _TABLE_KEYS["budget"])
    _check_keys(run, "run", _TABLE_KEYS["run"])

    return Config(
        live=LiveConfig(
            enabled=_as_bool(live.get("enabled"), "live.enabled", defaults.live.enabled)
        ),
        hitl=HitlConfig(auto=_as_bool(hitl.get("auto"), "hitl.auto", defaults.hitl.auto)),
        capability=CapabilityConfig(
            search=SearchConfig(
                provider=_as_str(
                    search.get("provider"),
                    "capability.search.provider",
                    defaults.capability.search.provider,
                )
            ),
            prompt=PromptConfig(
                provider=_as_str(
                    prompt.get("provider"),
                    "capability.prompt.provider",
                    defaults.capability.prompt.provider,
                ),
                directory=_as_str(
                    prompt.get("directory"),
                    "capability.prompt.directory",
                    defaults.capability.prompt.directory,
                ),
            ),
        ),
        budget=BudgetConfig(
            max_steps=_as_int(
                budget.get("max_steps"), "budget.max_steps", defaults.budget.max_steps
            ),
            max_wall=_as_str(budget.get("max_wall"), "budget.max_wall", defaults.budget.max_wall),
            max_cost=_as_float(budget.get("max_cost"), "budget.max_cost", defaults.budget.max_cost),
        ),
        run=RunConfig(dir=_as_str(run.get("dir"), "run.dir", defaults.run.dir)),
    )


def _live_from_env() -> bool | None:
    """Return the ``ORIGINWEAVE_LIVE`` override, or ``None`` when unset."""
    raw = os.environ.get(LIVE_ENV_VAR)
    if raw is None:
        return None
    value = raw.strip().lower()
    if value in _TRUE_VALUES:
        return True
    if value in _FALSE_VALUES:
        return False
    raise ConfigError(
        f"{LIVE_ENV_VAR} must be one of {sorted(_TRUE_VALUES | _FALSE_VALUES)}; got {raw!r}"
    )


def load(path: Path | None = None) -> Config:
    """Load and validate config, falling back to defaults when the file is absent.

    ``ORIGINWEAVE_LIVE`` overrides ``[live].enabled`` when set.
    """
    config_path = Path(CONFIG_FILENAME) if path is None else path
    if config_path.is_file():
        try:
            with config_path.open("rb") as handle:
                data = tomllib.load(handle)
        except (tomllib.TOMLDecodeError, OSError) as exc:
            raise ConfigError(f"invalid {config_path}: {exc}") from exc
        config = from_dict(data)
    else:
        config = Config()
    override = _live_from_env()
    if override is not None:
        config = replace(config, live=LiveConfig(enabled=override))
    config.validate()
    return config


def write_default(path: Path | None = None, *, force: bool = False) -> Path:
    """Write the default config, refusing to clobber unless ``force`` is set."""
    config_path = Path(CONFIG_FILENAME) if path is None else path
    if config_path.exists() and not force:
        raise FileExistsError(f"{config_path} already exists; pass --force to overwrite")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with config_path.open("wb") as handle:
        tomli_w.dump(Config().to_dict(), handle)
    return config_path
