"""Configuration loading and defaults for originweave.

The default configuration lives in the project-local ``originweave.toml`` and is
generated by ``originweave init``. Reads use the standard-library ``tomllib``;
writes use ``tomli-w``.

CLI flags take precedence over config values; missing keys fall back to the
defaults defined here. Credentials are never stored in config (env only).
"""

from __future__ import annotations

import re
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import tomli_w

CONFIG_FILENAME = "originweave.toml"

ALLOWED_SEARCH_PROVIDERS: frozenset[str] = frozenset({"exa", "parallel"})
ALLOWED_PROMPT_PROVIDERS: frozenset[str] = frozenset({"local", "langfuse"})
ALLOWED_MODEL_PROVIDERS: frozenset[str] = frozenset({"openai"})
ALLOWED_WORKER_PROVIDERS: frozenset[str] = frozenset({"local", "pi"})
# Pi tool allowlist (M6); ``search`` is the TS extension tool, the rest are Pi built-ins.
ALLOWED_WORKER_TOOLS: frozenset[str] = frozenset(
    {"search", "read", "grep", "find", "ls", "bash", "edit", "write"}
)

_TOP_LEVEL_KEYS: frozenset[str] = frozenset({"hitl", "capability", "worker", "run"})
_TABLE_KEYS: dict[str, frozenset[str]] = {
    "hitl": frozenset({"auto"}),
    "capability": frozenset({"search", "prompt", "model"}),
    "capability.search": frozenset({"provider"}),
    "capability.prompt": frozenset({"provider", "directory"}),
    "capability.model": frozenset({"provider", "model", "base_url"}),
    "worker": frozenset({"provider", "max_concurrency", "tools", "budget"}),
    "worker.budget": frozenset({"max_steps", "max_wall", "max_cost"}),
    "run": frozenset({"dir"}),
}


class ConfigError(ValueError):
    """Raised when a configuration value is missing or invalid."""


@dataclass(frozen=True)
class HitlConfig:
    auto: bool = False


@dataclass(frozen=True)
class SearchConfig:
    provider: str = "exa"


@dataclass(frozen=True)
class PromptConfig:
    provider: str = "local"
    directory: str = "prompts"


@dataclass(frozen=True)
class ModelConfig:
    provider: str = "openai"
    model: str = "deepseek-v4.1-flash"
    # Endpoint is supplied via the OPENAI_BASE_URL environment variable so that
    # internal hosts are never committed. Empty means "use the env var".
    base_url: str = ""


@dataclass(frozen=True)
class CapabilityConfig:
    search: SearchConfig = field(default_factory=SearchConfig)
    prompt: PromptConfig = field(default_factory=PromptConfig)
    model: ModelConfig = field(default_factory=ModelConfig)


@dataclass(frozen=True)
class BudgetConfig:
    max_steps: int = 60
    max_wall: str = "10m"
    max_cost: float = 2.0


@dataclass(frozen=True)
class WorkerConfig:
    provider: str = "pi"  # local | pi
    # Per-run cap on concurrent workers (enforced by the dispatcher, M6).
    max_concurrency: int = 1
    # Pi tool allowlist; empty means "no tools" (M6).
    tools: tuple[str, ...] = ()
    budget: BudgetConfig = field(default_factory=BudgetConfig)


@dataclass(frozen=True)
class RunConfig:
    dir: str = "runs"


@dataclass(frozen=True)
class Config:
    hitl: HitlConfig = field(default_factory=HitlConfig)
    capability: CapabilityConfig = field(default_factory=CapabilityConfig)
    worker: WorkerConfig = field(default_factory=WorkerConfig)
    run: RunConfig = field(default_factory=RunConfig)

    def to_dict(self) -> dict[str, Any]:
        """Render the config as a plain dict suitable for TOML serialisation."""
        return {
            "hitl": {"auto": self.hitl.auto},
            "capability": {
                "search": {"provider": self.capability.search.provider},
                "prompt": {
                    "provider": self.capability.prompt.provider,
                    "directory": self.capability.prompt.directory,
                },
                "model": {
                    "provider": self.capability.model.provider,
                    "model": self.capability.model.model,
                    "base_url": self.capability.model.base_url,
                },
            },
            "worker": {
                "provider": self.worker.provider,
                "max_concurrency": self.worker.max_concurrency,
                "tools": list(self.worker.tools),
                "budget": {
                    "max_steps": self.worker.budget.max_steps,
                    "max_wall": self.worker.budget.max_wall,
                    "max_cost": self.worker.budget.max_cost,
                },
            },
            "run": {"dir": self.run.dir},
        }

    def validate(self) -> None:
        """Validate cross-field invariants; raise :class:`ConfigError` on failure."""
        search = self.capability.search.provider
        if search not in ALLOWED_SEARCH_PROVIDERS:
            raise ConfigError(
                f"unknown search provider {search!r}; "
                f"expected one of {sorted(ALLOWED_SEARCH_PROVIDERS)}"
            )
        prompt = self.capability.prompt.provider
        if prompt not in ALLOWED_PROMPT_PROVIDERS:
            raise ConfigError(
                f"unknown prompt provider {prompt!r}; "
                f"expected one of {sorted(ALLOWED_PROMPT_PROVIDERS)}"
            )
        model = self.capability.model.provider
        if model not in ALLOWED_MODEL_PROVIDERS:
            raise ConfigError(
                f"unknown model provider {model!r}; "
                f"expected one of {sorted(ALLOWED_MODEL_PROVIDERS)}"
            )
        worker = self.worker.provider
        if worker not in ALLOWED_WORKER_PROVIDERS:
            raise ConfigError(
                f"unknown worker provider {worker!r}; "
                f"expected one of {sorted(ALLOWED_WORKER_PROVIDERS)}"
            )
        if self.worker.max_concurrency <= 0:
            raise ConfigError(
                f"worker.max_concurrency must be > 0, got {self.worker.max_concurrency}"
            )
        unknown_tools = sorted(set(self.worker.tools) - ALLOWED_WORKER_TOOLS)
        if unknown_tools:
            raise ConfigError(
                f"worker.tools: unknown tool(s) {unknown_tools}; "
                f"allowed: {sorted(ALLOWED_WORKER_TOOLS)}"
            )
        budget = self.worker.budget
        if budget.max_steps <= 0:
            raise ConfigError(f"worker.budget.max_steps must be > 0, got {budget.max_steps}")
        if budget.max_cost < 0:
            raise ConfigError(f"worker.budget.max_cost must be >= 0, got {budget.max_cost}")
        if not re.fullmatch(r"[1-9][0-9]*(?:ms|s|m|h|d)", budget.max_wall):
            raise ConfigError(
                "worker.budget.max_wall must be a positive integer followed by ms, s, m, h, or d"
            )


def _as_mapping(value: Any, where: str) -> Mapping[str, Any]:
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ConfigError(f"{where} must be a TOML table")
    return value


def _as_str(value: Any, where: str, default: str) -> str:
    if value is None:
        return default
    if not isinstance(value, str):
        raise ConfigError(f"{where} must be a string")
    return value


def _as_bool(value: Any, where: str, default: bool) -> bool:
    if value is None:
        return default
    if not isinstance(value, bool):
        raise ConfigError(f"{where} must be a boolean")
    return value


def _as_int(value: Any, where: str, default: int) -> int:
    if value is None:
        return default
    if not isinstance(value, int) or isinstance(value, bool):
        raise ConfigError(f"{where} must be an integer")
    return value


def _as_float(value: Any, where: str, default: float) -> float:
    if value is None:
        return default
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ConfigError(f"{where} must be a number")
    return float(value)


def _as_str_list(value: Any, where: str, default: tuple[str, ...]) -> tuple[str, ...]:
    if value is None:
        return default
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ConfigError(f"{where} must be a list of strings")
    return tuple(value)


def _check_keys(table: Mapping[str, Any], where: str, allowed: frozenset[str]) -> None:
    unknown = sorted(set(table) - allowed)
    if unknown:
        label = where or "config"
        raise ConfigError(f"{label}: unknown key(s) {unknown}; allowed: {sorted(allowed)}")


def from_dict(data: Mapping[str, Any]) -> Config:
    """Build a :class:`Config` from a parsed TOML mapping, filling in defaults."""
    defaults = Config()
    _check_keys(data, "", _TOP_LEVEL_KEYS)
    hitl = _as_mapping(data.get("hitl"), "hitl")
    capability = _as_mapping(data.get("capability"), "capability")
    search = _as_mapping(capability.get("search"), "capability.search")
    prompt = _as_mapping(capability.get("prompt"), "capability.prompt")
    model = _as_mapping(capability.get("model"), "capability.model")
    worker = _as_mapping(data.get("worker"), "worker")
    worker_budget = _as_mapping(worker.get("budget"), "worker.budget")
    run = _as_mapping(data.get("run"), "run")

    _check_keys(hitl, "hitl", _TABLE_KEYS["hitl"])
    _check_keys(capability, "capability", _TABLE_KEYS["capability"])
    _check_keys(search, "capability.search", _TABLE_KEYS["capability.search"])
    _check_keys(prompt, "capability.prompt", _TABLE_KEYS["capability.prompt"])
    _check_keys(model, "capability.model", _TABLE_KEYS["capability.model"])
    _check_keys(worker, "worker", _TABLE_KEYS["worker"])
    _check_keys(worker_budget, "worker.budget", _TABLE_KEYS["worker.budget"])
    _check_keys(run, "run", _TABLE_KEYS["run"])

    return Config(
        hitl=HitlConfig(auto=_as_bool(hitl.get("auto"), "hitl.auto", defaults.hitl.auto)),
        capability=CapabilityConfig(
            search=SearchConfig(
                provider=_as_str(
                    search.get("provider"),
                    "capability.search.provider",
                    defaults.capability.search.provider,
                )
            ),
            prompt=PromptConfig(
                provider=_as_str(
                    prompt.get("provider"),
                    "capability.prompt.provider",
                    defaults.capability.prompt.provider,
                ),
                directory=_as_str(
                    prompt.get("directory"),
                    "capability.prompt.directory",
                    defaults.capability.prompt.directory,
                ),
            ),
            model=ModelConfig(
                provider=_as_str(
                    model.get("provider"),
                    "capability.model.provider",
                    defaults.capability.model.provider,
                ),
                model=_as_str(
                    model.get("model"),
                    "capability.model.model",
                    defaults.capability.model.model,
                ),
                base_url=_as_str(
                    model.get("base_url"),
                    "capability.model.base_url",
                    defaults.capability.model.base_url,
                ),
            ),
        ),
        worker=WorkerConfig(
            provider=_as_str(
                worker.get("provider"),
                "worker.provider",
                defaults.worker.provider,
            ),
            max_concurrency=_as_int(
                worker.get("max_concurrency"),
                "worker.max_concurrency",
                defaults.worker.max_concurrency,
            ),
            tools=_as_str_list(
                worker.get("tools"),
                "worker.tools",
                defaults.worker.tools,
            ),
            budget=BudgetConfig(
                max_steps=_as_int(
                    worker_budget.get("max_steps"),
                    "worker.budget.max_steps",
                    defaults.worker.budget.max_steps,
                ),
                max_wall=_as_str(
                    worker_budget.get("max_wall"),
                    "worker.budget.max_wall",
                    defaults.worker.budget.max_wall,
                ),
                max_cost=_as_float(
                    worker_budget.get("max_cost"),
                    "worker.budget.max_cost",
                    defaults.worker.budget.max_cost,
                ),
            ),
        ),
        run=RunConfig(dir=_as_str(run.get("dir"), "run.dir", defaults.run.dir)),
    )


def load(path: Path | None = None) -> Config:
    """Load and validate config, falling back to defaults when the file is absent."""
    config_path = Path(CONFIG_FILENAME) if path is None else path
    if config_path.is_file():
        try:
            with config_path.open("rb") as handle:
                data = tomllib.load(handle)
        except (tomllib.TOMLDecodeError, OSError) as exc:
            raise ConfigError(f"invalid {config_path}: {exc}") from exc
        config = from_dict(data)
    else:
        config = Config()
    config.validate()
    return config


def write_default(path: Path | None = None, *, force: bool = False) -> Path:
    """Write the default config, refusing to clobber unless ``force`` is set."""
    config_path = Path(CONFIG_FILENAME) if path is None else path
    if config_path.exists() and not force:
        raise FileExistsError(f"{config_path} already exists; pass --force to overwrite")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with config_path.open("wb") as handle:
        tomli_w.dump(Config().to_dict(), handle)
    return config_path
