"""Configuration loading and defaults for originweave.

The default configuration lives in the project-local ``originweave.toml`` and is
generated by ``originweave init``. Reads use the standard-library ``tomllib``;
writes use ``tomli-w``.

CLI flags take precedence over config values; missing keys fall back to the
defaults defined here. Credentials are never stored in config (env only).
"""

from __future__ import annotations

import math
import os
import re
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import tomli_w

CONFIG_FILENAME = "originweave.toml"

ALLOWED_SEARCH_PROVIDERS: frozenset[str] = frozenset({"exa", "parallel"})
ALLOWED_PROMPT_PROVIDERS: frozenset[str] = frozenset({"local", "langfuse"})
ALLOWED_MODEL_PROVIDERS: frozenset[str] = frozenset({"openai"})
ALLOWED_WORKER_PROVIDERS: frozenset[str] = frozenset({"local", "pi"})
# Where a Worker call executes: in-process (temporary) or the Docker runtime.
ALLOWED_WORKER_EXECUTION: frozenset[str] = frozenset({"in-process", "container"})
# How Pi calls use the runtime container.  ``per-run`` is deliberately scoped to
# Pi: it saves the Pi/Node startup cost without changing the local worker contract.
ALLOWED_CONTAINER_SCOPE: frozenset[str] = frozenset({"per-call", "per-run"})
# Pi tool allowlist (M6); ``search`` is the TS extension tool, the rest are Pi built-ins.
ALLOWED_WORKER_TOOLS: frozenset[str] = frozenset(
    {"search", "read", "grep", "find", "ls", "bash", "edit", "write"}
)
# What happens when a single Worker call exceeds [worker].heartbeat_timeout (I4).
ALLOWED_HEARTBEAT_ON_TIMEOUT: frozenset[str] = frozenset({"release", "fail"})
# Sanity ceiling on [worker].max_concurrency (I4); protects the host from a runaway pool.
MAX_WORKER_CONCURRENCY = 16
# Duration units accepted by [worker.budget].max_wall and the [worker].heartbeat_* keys.
_DURATION_UNITS: dict[str, float] = {
    "ms": 0.001,
    "s": 1.0,
    "m": 60.0,
    "h": 3600.0,
    "d": 86400.0,
}
_DURATION_RE = re.compile(r"([1-9][0-9]*)(ms|s|m|h|d)")

_TOP_LEVEL_KEYS: frozenset[str] = frozenset(
    {"hitl", "capability", "worker", "run", "project", "storage"}
)
_TABLE_KEYS: dict[str, frozenset[str]] = {
    "hitl": frozenset({"auto"}),
    "capability": frozenset({"search", "prompt", "model"}),
    "capability.search": frozenset({"provider"}),
    "capability.prompt": frozenset({"provider", "directory"}),
    "capability.model": frozenset({"provider", "model", "base_url"}),
    "worker": frozenset(
        {
            "provider",
            "execution",
            "image",
            "container_scope",
            "max_concurrency",
            "tools",
            "heartbeat_interval",
            "heartbeat_timeout",
            "heartbeat_on_timeout",
            "budget",
        }
    ),
    "worker.budget": frozenset({"max_steps", "max_wall", "max_cost"}),
    "run": frozenset({"dir"}),
    "project": frozenset({"dir"}),
    "storage": frozenset({"db"}),
}


class ConfigError(ValueError):
    """Raised when a configuration value is missing or invalid."""


def parse_duration(text: str, where: str = "duration") -> float:
    """Parse a positive duration such as ``"10m"`` into seconds.

    The grammar is a positive integer followed by ``ms|s|m|h|d`` (no whitespace).
    Used by ``[worker.budget].max_wall`` and the heartbeat lease settings (I4).
    """
    match = _DURATION_RE.fullmatch(text)
    if match is None:
        raise ConfigError(
            f"{where} must be a positive integer followed by ms, s, m, h, or d; got {text!r}"
        )
    return int(match.group(1)) * _DURATION_UNITS[match.group(2)]


@dataclass(frozen=True)
class HitlConfig:
    auto: bool = False


@dataclass(frozen=True)
class SearchConfig:
    provider: str = "exa"


@dataclass(frozen=True)
class PromptConfig:
    provider: str = "local"
    directory: str = "prompts"


@dataclass(frozen=True)
class ModelConfig:
    provider: str = "openai"
    model: str = "deepseek-v4.1-flash"
    # Endpoint is supplied via the OPENAI_BASE_URL environment variable so that
    # internal hosts are never committed. Empty means "use the env var".
    base_url: str = ""


@dataclass(frozen=True)
class CapabilityConfig:
    search: SearchConfig = field(default_factory=SearchConfig)
    prompt: PromptConfig = field(default_factory=PromptConfig)
    model: ModelConfig = field(default_factory=ModelConfig)


@dataclass(frozen=True)
class BudgetConfig:
    max_steps: int = 60
    max_wall: str = "10m"
    max_cost: float = 2.0


@dataclass(frozen=True)
class WorkerConfig:
    provider: str = "pi"  # local | pi (the execution body inside the container)
    # Where a Worker call runs. Container is the production default.
    execution: str = "container"  # in-process | container
    # Runtime image used when execution == "container" (M3a; build it with `make image`).
    image: str = "originweave-runtime:latest"
    # ``per-run`` reuses one Pi runtime container for this run; ``per-call`` is
    # the strict isolation mode and starts a fresh container for every call.
    container_scope: str = "per-run"  # per-call | per-run
    # Cap on concurrent workers (== concurrent containers under container-per-worker, M6).
    max_concurrency: int = 1
    # Pi tool allowlist; empty means "no tools" (M6).
    tools: tuple[str, ...] = ()
    # Liveness lease for a single Worker call (I4): the engine writes HEARTBEAT every
    # ``heartbeat_interval`` and treats a call exceeding ``heartbeat_timeout`` as dead,
    # then either RELEASEs the Intent (``release``) or fails the run (``fail``).
    heartbeat_interval: str = "15s"
    heartbeat_timeout: str = "5m"
    heartbeat_on_timeout: str = "release"  # release | fail
    budget: BudgetConfig = field(default_factory=BudgetConfig)


@dataclass(frozen=True)
class RunConfig:
    dir: str = "runs"


@dataclass(frozen=True)
class ProjectConfig:
    dir: str = "projects"


@dataclass(frozen=True)
class StorageConfig:
    # Global SQLite database: runs/projects static metadata (the live event log
    # stays ``events.jsonl``; migrated/imported runs may also store events here).
    db: str = "originweave.db"


@dataclass(frozen=True)
class Config:
    hitl: HitlConfig = field(default_factory=HitlConfig)
    capability: CapabilityConfig = field(default_factory=CapabilityConfig)
    worker: WorkerConfig = field(default_factory=WorkerConfig)
    run: RunConfig = field(default_factory=RunConfig)
    project: ProjectConfig = field(default_factory=ProjectConfig)
    storage: StorageConfig = field(default_factory=StorageConfig)

    def to_dict(self) -> dict[str, Any]:
        """Render the config as a plain dict suitable for TOML serialisation."""
        return {
            "hitl": {"auto": self.hitl.auto},
            "capability": {
                "search": {"provider": self.capability.search.provider},
                "prompt": {
                    "provider": self.capability.prompt.provider,
                    "directory": self.capability.prompt.directory,
                },
                "model": {
                    "provider": self.capability.model.provider,
                    "model": self.capability.model.model,
                    "base_url": self.capability.model.base_url,
                },
            },
            "worker": {
                "provider": self.worker.provider,
                "execution": self.worker.execution,
                "image": self.worker.image,
                "container_scope": self.worker.container_scope,
                "max_concurrency": self.worker.max_concurrency,
                "tools": list(self.worker.tools),
                "heartbeat_interval": self.worker.heartbeat_interval,
                "heartbeat_timeout": self.worker.heartbeat_timeout,
                "heartbeat_on_timeout": self.worker.heartbeat_on_timeout,
                "budget": {
                    "max_steps": self.worker.budget.max_steps,
                    "max_wall": self.worker.budget.max_wall,
                    "max_cost": self.worker.budget.max_cost,
                },
            },
            "run": {"dir": self.run.dir},
            "project": {"dir": self.project.dir},
            "storage": {"db": self.storage.db},
        }

    def validate(self) -> None:
        """Validate cross-field invariants; raise :class:`ConfigError` on failure."""
        search = self.capability.search.provider
        if search not in ALLOWED_SEARCH_PROVIDERS:
            raise ConfigError(
                f"unknown search provider {search!r}; "
                f"expected one of {sorted(ALLOWED_SEARCH_PROVIDERS)}"
            )
        prompt = self.capability.prompt.provider
        if prompt not in ALLOWED_PROMPT_PROVIDERS:
            raise ConfigError(
                f"unknown prompt provider {prompt!r}; "
                f"expected one of {sorted(ALLOWED_PROMPT_PROVIDERS)}"
            )
        model = self.capability.model.provider
        if model not in ALLOWED_MODEL_PROVIDERS:
            raise ConfigError(
                f"unknown model provider {model!r}; "
                f"expected one of {sorted(ALLOWED_MODEL_PROVIDERS)}"
            )
        if not self.capability.model.model:
            raise ConfigError("capability.model.model must be a non-empty string")
        worker = self.worker.provider
        if worker not in ALLOWED_WORKER_PROVIDERS:
            raise ConfigError(
                f"unknown worker provider {worker!r}; "
                f"expected one of {sorted(ALLOWED_WORKER_PROVIDERS)}"
            )
        execution = self.worker.execution
        if execution not in ALLOWED_WORKER_EXECUTION:
            raise ConfigError(
                f"unknown worker.execution {execution!r}; "
                f"expected one of {sorted(ALLOWED_WORKER_EXECUTION)}"
            )
        if execution == "container" and not self.worker.image:
            raise ConfigError("worker.image must be a non-empty string when execution='container'")
        scope = self.worker.container_scope
        if scope not in ALLOWED_CONTAINER_SCOPE:
            raise ConfigError(
                f"unknown worker.container_scope {scope!r}; "
                f"expected one of {sorted(ALLOWED_CONTAINER_SCOPE)}"
            )
        if scope == "per-run" and (worker != "pi" or execution != "container"):
            raise ConfigError(
                "worker.container_scope='per-run' requires "
                "worker.provider='pi' and worker.execution='container'"
            )
        if self.worker.max_concurrency <= 0:
            raise ConfigError(
                f"worker.max_concurrency must be > 0, got {self.worker.max_concurrency}"
            )
        if self.worker.max_concurrency > MAX_WORKER_CONCURRENCY:
            raise ConfigError(
                f"worker.max_concurrency must be <= {MAX_WORKER_CONCURRENCY}, "
                f"got {self.worker.max_concurrency}"
            )
        unknown_tools = sorted(set(self.worker.tools) - ALLOWED_WORKER_TOOLS)
        if unknown_tools:
            raise ConfigError(
                f"worker.tools: unknown tool(s) {unknown_tools}; "
                f"allowed: {sorted(ALLOWED_WORKER_TOOLS)}"
            )
        if self.worker.heartbeat_on_timeout not in ALLOWED_HEARTBEAT_ON_TIMEOUT:
            raise ConfigError(
                "worker.heartbeat_on_timeout must be one of "
                f"{sorted(ALLOWED_HEARTBEAT_ON_TIMEOUT)}; "
                f"got {self.worker.heartbeat_on_timeout!r}"
            )
        interval = parse_duration(self.worker.heartbeat_interval, "worker.heartbeat_interval")
        timeout = parse_duration(self.worker.heartbeat_timeout, "worker.heartbeat_timeout")
        if interval >= timeout:
            raise ConfigError(
                "worker.heartbeat_interval must be < worker.heartbeat_timeout "
                f"(got {self.worker.heartbeat_interval} >= {self.worker.heartbeat_timeout})"
            )
        budget = self.worker.budget
        if budget.max_steps <= 0:
            raise ConfigError(f"worker.budget.max_steps must be > 0, got {budget.max_steps}")
        if not math.isfinite(budget.max_cost) or budget.max_cost < 0:
            raise ConfigError(
                f"worker.budget.max_cost must be finite and >= 0, got {budget.max_cost}"
            )
        parse_duration(budget.max_wall, "worker.budget.max_wall")
        if not self.run.dir:
            raise ConfigError("run.dir must be a non-empty string")
        if not self.project.dir:
            raise ConfigError("project.dir must be a non-empty string")
        if not self.storage.db:
            raise ConfigError("storage.db must be a non-empty string")


def _as_mapping(value: Any, where: str) -> Mapping[str, Any]:
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ConfigError(f"{where} must be a TOML table")
    return value


def _as_str(value: Any, where: str, default: str) -> str:
    if value is None:
        return default
    if not isinstance(value, str):
        raise ConfigError(f"{where} must be a string")
    return value


def _as_bool(value: Any, where: str, default: bool) -> bool:
    if value is None:
        return default
    if not isinstance(value, bool):
        raise ConfigError(f"{where} must be a boolean")
    return value


def _as_int(value: Any, where: str, default: int) -> int:
    if value is None:
        return default
    if not isinstance(value, int) or isinstance(value, bool):
        raise ConfigError(f"{where} must be an integer")
    return value


def _as_float(value: Any, where: str, default: float) -> float:
    if value is None:
        return default
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ConfigError(f"{where} must be a number")
    return float(value)


def _as_str_list(value: Any, where: str, default: tuple[str, ...]) -> tuple[str, ...]:
    if value is None:
        return default
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ConfigError(f"{where} must be a list of strings")
    return tuple(value)


def _check_keys(table: Mapping[str, Any], where: str, allowed: frozenset[str]) -> None:
    unknown = sorted(set(table) - allowed)
    if unknown:
        label = where or "config"
        raise ConfigError(f"{label}: unknown key(s) {unknown}; allowed: {sorted(allowed)}")


def from_dict(data: Mapping[str, Any]) -> Config:
    """Build a :class:`Config` from a parsed TOML mapping, filling in defaults."""
    defaults = Config()
    _check_keys(data, "", _TOP_LEVEL_KEYS)
    hitl = _as_mapping(data.get("hitl"), "hitl")
    capability = _as_mapping(data.get("capability"), "capability")
    search = _as_mapping(capability.get("search"), "capability.search")
    prompt = _as_mapping(capability.get("prompt"), "capability.prompt")
    model = _as_mapping(capability.get("model"), "capability.model")
    worker = _as_mapping(data.get("worker"), "worker")
    worker_budget = _as_mapping(worker.get("budget"), "worker.budget")
    run = _as_mapping(data.get("run"), "run")
    project = _as_mapping(data.get("project"), "project")
    storage = _as_mapping(data.get("storage"), "storage")

    _check_keys(hitl, "hitl", _TABLE_KEYS["hitl"])
    _check_keys(capability, "capability", _TABLE_KEYS["capability"])
    _check_keys(search, "capability.search", _TABLE_KEYS["capability.search"])
    _check_keys(prompt, "capability.prompt", _TABLE_KEYS["capability.prompt"])
    _check_keys(model, "capability.model", _TABLE_KEYS["capability.model"])
    _check_keys(worker, "worker", _TABLE_KEYS["worker"])
    _check_keys(worker_budget, "worker.budget", _TABLE_KEYS["worker.budget"])
    _check_keys(run, "run", _TABLE_KEYS["run"])
    _check_keys(project, "project", _TABLE_KEYS["project"])
    _check_keys(storage, "storage", _TABLE_KEYS["storage"])

    return Config(
        hitl=HitlConfig(auto=_as_bool(hitl.get("auto"), "hitl.auto", defaults.hitl.auto)),
        capability=CapabilityConfig(
            search=SearchConfig(
                provider=_as_str(
                    search.get("provider"),
                    "capability.search.provider",
                    defaults.capability.search.provider,
                )
            ),
            prompt=PromptConfig(
                provider=_as_str(
                    prompt.get("provider"),
                    "capability.prompt.provider",
                    defaults.capability.prompt.provider,
                ),
                directory=_as_str(
                    prompt.get("directory"),
                    "capability.prompt.directory",
                    defaults.capability.prompt.directory,
                ),
            ),
            model=ModelConfig(
                provider=_as_str(
                    model.get("provider"),
                    "capability.model.provider",
                    defaults.capability.model.provider,
                ),
                model=_as_str(
                    model.get("model"),
                    "capability.model.model",
                    defaults.capability.model.model,
                ),
                base_url=_as_str(
                    model.get("base_url"),
                    "capability.model.base_url",
                    defaults.capability.model.base_url,
                ),
            ),
        ),
        worker=WorkerConfig(
            provider=_as_str(
                worker.get("provider"),
                "worker.provider",
                defaults.worker.provider,
            ),
            execution=_as_str(
                worker.get("execution"),
                "worker.execution",
                defaults.worker.execution,
            ),
            image=_as_str(
                worker.get("image"),
                "worker.image",
                defaults.worker.image,
            ),
            container_scope=_as_str(
                worker.get("container_scope"),
                "worker.container_scope",
                defaults.worker.container_scope,
            ),
            max_concurrency=_as_int(
                worker.get("max_concurrency"),
                "worker.max_concurrency",
                defaults.worker.max_concurrency,
            ),
            tools=_as_str_list(
                worker.get("tools"),
                "worker.tools",
                defaults.worker.tools,
            ),
            heartbeat_interval=_as_str(
                worker.get("heartbeat_interval"),
                "worker.heartbeat_interval",
                defaults.worker.heartbeat_interval,
            ),
            heartbeat_timeout=_as_str(
                worker.get("heartbeat_timeout"),
                "worker.heartbeat_timeout",
                defaults.worker.heartbeat_timeout,
            ),
            heartbeat_on_timeout=_as_str(
                worker.get("heartbeat_on_timeout"),
                "worker.heartbeat_on_timeout",
                defaults.worker.heartbeat_on_timeout,
            ),
            budget=BudgetConfig(
                max_steps=_as_int(
                    worker_budget.get("max_steps"),
                    "worker.budget.max_steps",
                    defaults.worker.budget.max_steps,
                ),
                max_wall=_as_str(
                    worker_budget.get("max_wall"),
                    "worker.budget.max_wall",
                    defaults.worker.budget.max_wall,
                ),
                max_cost=_as_float(
                    worker_budget.get("max_cost"),
                    "worker.budget.max_cost",
                    defaults.worker.budget.max_cost,
                ),
            ),
        ),
        run=RunConfig(dir=_as_str(run.get("dir"), "run.dir", defaults.run.dir)),
        project=ProjectConfig(dir=_as_str(project.get("dir"), "project.dir", defaults.project.dir)),
        storage=StorageConfig(db=_as_str(storage.get("db"), "storage.db", defaults.storage.db)),
    )


def save(config: Config, path: Path | None = None) -> Path:
    """Write ``config`` to ``originweave.toml``, overwriting any existing file.

    Validates first so a bad ``UpdateSettings`` can never persist an invalid file. The
    file is regenerated from :meth:`Config.to_dict`, so any comments or unrelated
    formatting in a hand-edited file are not preserved (semantics are the contract).
    """
    config.validate()
    config_path = Path(CONFIG_FILENAME) if path is None else path
    config_path.parent.mkdir(parents=True, exist_ok=True)
    # Write to a sibling temp file then replace, so a crash mid-write cannot corrupt
    # the live config.
    tmp_path = config_path.with_name(f".{config_path.name}.tmp")
    with tmp_path.open("wb") as handle:
        tomli_w.dump(config.to_dict(), handle)
    os.replace(tmp_path, config_path)
    return config_path


def load(path: Path | None = None) -> Config:
    """Load and validate config, falling back to defaults when the file is absent."""
    config_path = Path(CONFIG_FILENAME) if path is None else path
    if config_path.is_file():
        try:
            with config_path.open("rb") as handle:
                data = tomllib.load(handle)
        except (tomllib.TOMLDecodeError, OSError) as exc:
            raise ConfigError(f"invalid {config_path}: {exc}") from exc
        config = from_dict(data)
    else:
        config = Config()
    config.validate()
    return config


def write_default(path: Path | None = None, *, force: bool = False) -> Path:
    """Write the default config, refusing to clobber unless ``force`` is set."""
    config_path = Path(CONFIG_FILENAME) if path is None else path
    if config_path.exists() and not force:
        raise FileExistsError(f"{config_path} already exists; pass --force to overwrite")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with config_path.open("wb") as handle:
        tomli_w.dump(Config().to_dict(), handle)
    return config_path
